INSERT INTO USERS
VALUES (1,'abc','123');

INSERT INTO LOCATIONS
VALUES (1 ,'LONDON');
INSERT INTO LOCATIONS
VALUES (2 ,'MANCHESTER');
INSERT INTO LOCATIONS
VALUES (3 ,'LIVERPOOL');
INSERT INTO LOCATIONS
VALUES (4 ,'BERLIN');
INSERT INTO LOCATIONS
VALUES (5 ,'TOKYO');
INSERT INTO LOCATIONS
VALUES (6 ,'DUBAI');

INSERT INTO KITS
VALUES (1 ,'BLUE');
INSERT INTO KITS
VALUES (2 ,'RED');
INSERT INTO KITS
VALUES (3 ,'WHITE');
INSERT INTO KITS
VALUES (4 ,'YELLOW');

INSERT INTO STADIUM
VALUES (1 ,'STAMFORD BRIDGE', 1, 80000);
INSERT INTO STADIUM
VALUES (2 ,'EMIRATES STADIUM', 1, 90000);
INSERT INTO STADIUM
VALUES (3 ,'OLD TRAFORD STADIUM', 2, 75000);
INSERT INTO STADIUM
VALUES (4 ,'ETIHAD STADIUM', 2, 100000);
INSERT INTO STADIUM
VALUES (5 ,'ANFIELD STADIUM', 3, 97500);
INSERT INTO STADIUM
VALUES (6 ,'WHITE HART-LANE', 1, 50000);
INSERT INTO STADIUM
VALUES (7 ,'KC STADIUM', 2, 47000);
INSERT INTO STADIUM
VALUES (8,'GOODISON PARK', 3, 49000);

INSERT INTO OWNERS
VALUES (1 ,'ROMAN', 1);
INSERT INTO OWNERS
VALUES (2 ,'AMIR', 6);
INSERT INTO OWNERS
VALUES (3 ,'CHE LOE', 5);
INSERT INTO OWNERS
VALUES (4,'ABRAHAM', 3);
INSERT INTO OWNERS
VALUES (5 ,'SIR RICHARD', 2);
INSERT INTO OWNERS
VALUES (6 ,'YOKOSHAMA', 5);

INSERT INTO COACHES
VALUES (1 ,'JORAH', 2);
INSERT INTO COACHES
VALUES (2 ,'CERCIE', 4);
INSERT INTO COACHES
VALUES (3 ,'VANGAAL', 1);
INSERT INTO COACHES
VALUES (4,'MORINHO', 6);
INSERT INTO COACHES
VALUES (5 ,'BENETIZ', 1);
INSERT INTO COACHES
VALUES (6 ,'GOMEZ', 2);
INSERT INTO COACHES
VALUES (7 ,'JAIME', 3);
INSERT INTO COACHES
VALUES (8 ,'WENGER', 5);


INSERT INTO SPONSORS
VALUES (1 ,'NIKE', 2, 1);
INSERT INTO SPONSORS
VALUES (2 ,'ADDIDAS', 2, 4);
INSERT INTO SPONSORS
VALUES (3 ,'PUMA', 3, 2);
INSERT INTO SPONSORS
VALUES (4 ,'REEBOK', 4, 3);
INSERT INTO SPONSORS
VALUES (5 ,'SAMSUNG', 1, 4);
INSERT INTO SPONSORS
VALUES (6 ,'FLYEMIRATES', 6, 6);


INSERT INTO TEAMS
VALUES (1 ,'ARSENAL', 2, 1, 12, 6, 2, 4, 2, 2, 2);
INSERT INTO TEAMS
VALUES (2 ,'CHELSEA', 1, 6, 13, 7, 3, 3, 4, 1, 4);
INSERT INTO TEAMS
VALUES (3 ,'MAN UTD', 3, 7, 10, 5, 2, 3, 6, 4, 3);
INSERT INTO TEAMS
VALUES (4 ,'MAN CITY', 4, 8, 11, 9, 2, 0, 3, 3, 2);
INSERT INTO TEAMS
VALUES (5 ,'LIVERPOOL', 5, 5, 9, 4, 3, 2, 1, 1, 1);
INSERT INTO TEAMS
VALUES (6 ,'TOTENHUM', 6, 3, 10, 3, 5, 2, 2, 2, 3);
INSERT INTO TEAMS
VALUES (7 ,'HULL CITY', 7, 4, 8, 4, 4, 0, 1, 3, 5);
INSERT INTO TEAMS
VALUES (8 ,'EVERTON',   8, 2, 6, 2, 1, 3, 4,4, 6);


INSERT  INTO PLAYERS
VALUES (1, 'MICHEAL', '01-JAN-84',1, 12, 2, NULL, 7, 1);
INSERT  INTO PLAYERS
VALUES (2, 'ROBINAL', '02-JUL-81',6, 9, 2, NULL, 7, 2);
INSERT INTO PLAYERS
VALUES (3, 'KING', '11-AUG-87',1, NULL, NULL,14, 8, 3);
INSERT INTO PLAYERS
VALUES (4, 'CECH', '21-FEB-85',5, NULL,  NULL, 15,3, 2);
INSERT INTO PLAYERS
VALUES (5, 'LAMPARD', '22-SEP-82',2, 8, 12, NULL, 4, 4);
INSERT INTO PLAYERS
VALUES (6, 'DROGBA', '30-OCT-92',2, 21, 4, NULL, 6, 5);
INSERT  INTO PLAYERS
VALUES (7, 'OZIL', '21-FEB-91',4, 7, 20, NULL,5, 3);
INSERT  INTO PLAYERS
VALUES (8, 'SANCHEZ', '24-MAR-90',3, 22, 10, NULL, 3,2);
INSERT  INTO PLAYERS
VALUES (9, 'ROONEY', '03-APR-87',1, 25, 8, NULL, 8, 5);
INSERT  INTO PLAYERS
VALUES (10, 'SILVA', '04-NOV-93',3, 12, 18, NULL,5, 1);
INSERT  INTO PLAYERS
VALUES (11, 'LUCAS', '09-MAY-95',4, 13, 9, NULL, 2, 4);
INSERT  INTO PLAYERS
VALUES (12, 'KNEAN', '10-JUN-89',2, 19, 10, NULL, 1, 6);


INSERT INTO POSITIONS
VALUES( 1, 'STRIKER');
INSERT INTO POSITIONS
VALUES( 2, 'DEFENDER');
INSERT INTO POSITIONS
VALUES( 3, 'DEFENDER');
INSERT INTO POSITIONS
VALUES( 4, 'GOAL-KEEPER');
INSERT INTO POSITIONS
VALUES( 5, 'MID-FIELDER');
INSERT INTO POSITIONS
VALUES( 6, 'STRIKER');
INSERT INTO POSITIONS
VALUES( 7, 'MID-FIELDER');
INSERT INTO POSITIONS
VALUES( 8, 'STRIKER');
INSERT INTO POSITIONS
VALUES( 9, 'STRIKER');
INSERT INTO POSITIONS
VALUES( 10, 'MID-FIELDER');
INSERT INTO POSITIONS
VALUES( 11, 'STRIKER');
INSERT INTO POSITIONS
VALUES( 12, 'DEFENDER');
INSERT INTO POSITIONS
VALUES( 8, 'MID-FIELDER');
INSERT INTO POSITIONS
VALUES( 1, 'MID-FIELDER');
INSERT INTO POSITIONS
VALUES( 9, 'MID-FIELDER');
